#ifndef QNORMTRANSPORT_GLOBAL_H
#define QNORMTRANSPORT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QNORMTRANSPORT_LIBRARY)
#  define QNORMTRANSPORTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QNORMTRANSPORTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QNORMTRANSPORT_GLOBAL_H
